title: "My Portfolio"
description: "A professional portfolio showcasing development and testing projects."
baseurl: ""  # If publishing at yourusername.github.io, leave empty
url: "https://AaronL-98.github.io/"  # Update with actual GitHub Pages URL

markdown: kramdown
theme: minima  # Or remove if using purely custom layouts

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:title/
  logs:
    output: false # or true if you want each log to have its own page
    permalink: /logs/:project/:title/

# Build settings
exclude:
  - "node_modules"
  - "Gemfile.lock"
  - "vendor"
  - ".bundle"
  - ".jekyll-cache"
  - "_site"

# Optional Jekyll plugins (add or remove as needed)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Misc
# future: true
# incremental: false
