title: "Portfolio of Aaron Lewis"
description: "A portfolio showcasing my game development and other projects with devopment logs."
baseurl: ""  # Leave empty if the site is deployed at the root
url: "https://yourusername.github.io/portfolio"  # Update with your GitHub Pages URL
theme: minima  # or set to custom theme if you have one

# Site settings
markdown: kramdown
permalink: pretty

# Collections (for Projects and Devlogs)
collections:
  projects:
    output: true
    permalink: /projects/:path/
  devlogs:
    output: true
    permalink: /devlog/:path/

# Include CSS assets
sass:
  style: compressed

# Navigation Links
header_pages:
  - index.md
  - projects.md
  - devlog.md
  - contact.md
