title: "Your Portfolio Site"
description: "Showcasing computer game development and devlogs."
url: "https://aaronl-98.github.io/" # GitHub Pages URL
baseurl: "" # If using a subpath, set it here, e.g. "/portfolio"

# Jekyll settings
markdown: kramdown
permalink: pretty

# Theme or custom
theme: minima # or remove if you want a fully custom approach

# Collections for Projects & Devlogs
collections:
  projects:
    output: true
    permalink: /projects/:title/
  devlogs:
    output: true
    permalink: /devlog/:title/

# Enable plugins if needed, e.g. jekyll-seo-tag, etc.
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
exclude:
  - "node_modules"
  - "Gemfile"
  - "Gemfile.lock"
  - ".github"
  - "README.md"

# If using GitHub Pages with a custom build, you may need these lines:
# future: true
# incremental: false
