title: "My Portfolio"
description: "A professional portfolio showcasing development and testing projects."
url: "https://AaronL-98.github.io/" # GitHub Pages URL
markdown: kramdown
# theme: minima  # Or remove if using purely custom layouts

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:title/
  logs:
    output: true
    permalink: /logs/:title/


# Build settings
# Exclude typical build directories
exclude:
  - "node_modules"
  - "Gemfile"
  - "Gemfile.lock"
  - "vendor"
  - ".gitignore"
  - "README.md"
  - ".bundle"
  - ".jekyll-cache"
  - "_site"

# Optional Jekyll plugins (add or remove as needed)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Misc
# future: true
# incremental: false
